name: Java Fibonacci App with Maven

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test